name: Tag for release on main

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: install dependencies
      run: npm ci
    - name: load bot signing key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo "loading key"
        mkdir -p /home/runner/.ssh
        echo "${{secrets.BOT_SSH_KEY}}" > /home/runner/.ssh/bot
        chmod 600 /home/runner/.ssh/bot
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add /home/runner/.ssh/bot
        echo "key added:"
        ssh-add -l
    - name: configure git
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo "enforcing signed commits & tags"
        git config --global user.signingkey "/home/runner/.ssh/bot"
        git config --global commit.gpgsign "true"
        git config --global gpg.format "ssh"
        git config --global tag.gpgSign "true"
        echo "adding andrew-chang-dewitt-bot as git user"
        git config --global user.email "${{secrets.BOT_EMAIL}}"
        git config --global user.name "andrew-chang-dewitt-bot"
        echo "git configured:"
        git config -l
    - name: release
      run: |
        npm run release
        export TAG=$(git describe --tags --abbrev=0)
        echo "release $TAG made with updated changelog:"
        cat CHANGELOG.md
    # - name: get release body
    #   id: get-release-body
    #   run: |
    #     echo "BODY=$(git tag --format='# %(*subject)

    #     %(*body)' --contains)" >> $GITHUB_OUTPUT
