name: Tag for release on main

on:
  push:
    branches:
      - main

jobs:
  bump_and_tag:
    name: "Bump, tag, and push"
    runs-on: ubuntu-latest
    # skip if commit is a version release
    if: "!contains(github.event.head_commit.message, 'chore(release):')"

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{secrets.BOT_SSH_KEY}}
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: install dependencies
      run: npm ci
    - name: configure bot for git
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{secrets.BOT_SSH_KEY}}" > /home/runner/.ssh/bot
        chmod 600 /home/runner/.ssh/bot
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add /home/runner/.ssh/bot
        git config --global user.signingkey "/home/runner/.ssh/bot"
        git config --global commit.gpgsign "true"
        git config --global gpg.format "ssh"
        git config --global tag.gpgSign "true"
        git config --global user.email "${{secrets.BOT_EMAIL}}"
        git config --global user.name "andrew-chang-dewitt-bot"
    - name: prepare to stage release
      run: git checkout -b bot/release-staging
    - name: create release commit & tag
      run: npm run release
    - name: get changelog for new release
      run: node scripts/getChanges.js
    - name: get changelog for new release
      run: node scripts/getChanges.js
    - name: check release
      run: |
        if [ -s BODY.md ]; then
        echo "RELEASE=0" >> "$GITHUB_OUTPUT"
        else
        echo "RELEASE=1" >> "$GITHUB_OUTPUT"
        fi
    - name: merge release & push
      if: steps.check_release.outputs.RELEASE == 0
      run: |
        git checkout main
        git merge bot/release-staging
        git push --follow-tags origin main
    - name: cleanup
      run: git branch -D bot/release-staging
